In [2]:
import numpy as np
M1 = [[0, 0], [0.5, 0.5]]
M2 = [[0.3, 0.7], [0.7, 0.3]]
M3 = [[0.5, 0.5], [0.6, 0.4]]
M4 = [[0, 1], [0, 1]]
M = [M1, M2, M3, M4] 

In [6]:
#路径从2开始
ls_path = [2]
for i in range(1, 4): #遍历出所有的组合
    paths = []
    for _, r in enumerate(ls_path):
        temp = np.transpose(r)
        paths.append(np.append(temp, 1))
        paths.append(np.append(temp, 2))
    ls_path = paths.copy()
ls_path = [np.append(r, 2) for _, r in enumerate(ls_path)]


In [7]:
ls_path #路径如下

[array([2, 1, 1, 1, 2]),
 array([2, 1, 1, 2, 2]),
 array([2, 1, 2, 1, 2]),
 array([2, 1, 2, 2, 2]),
 array([2, 2, 1, 1, 2]),
 array([2, 2, 1, 2, 2]),
 array([2, 2, 2, 1, 2]),
 array([2, 2, 2, 2, 2])]

In [10]:
pr = []
for row in ls_path:
    p = 1
    for i in range(len(row) - 1): #计算概率
        a = row[i]
        b = row[i + 1]
        p *= M[i][a - 1][b - 1]
    print("@@@" + "->".join([str(x) for x in row.tolist()]), end="||")
    print(f"概率为{p}")
    pr.append((row.tolist(), p))
pr = sorted(pr, key=lambda x: x[1], reverse=True)


@@@2->1->1->1->2 概率为0.075
@@@2->1->1->2->2 概率为0.075
@@@2->1->2->1->2 概率为0.21
@@@2->1->2->2->2 概率为0.13999999999999999
@@@2->2->1->1->2 概率为0.175
@@@2->2->1->2->2 概率为0.175
@@@2->2->2->1->2 概率为0.09
@@@2->2->2->2->2 概率为0.06
